#!/usr/bin/env python3

import argparse
import ipaddress
import os
import re
import subprocess
import sys

DEFAULT_COUNTRY_CODES = "CN US"
COUNTRY_CODE_RE = re.compile(r"^[A-Z]{2}$")


class RuleGenerationError(Exception):
    pass


def country_codes_from_env():
    raw = os.environ.get("CC", "").strip() or DEFAULT_COUNTRY_CODES
    country_codes = set()
    for value in raw.split():
        country_code = value.upper()
        if not COUNTRY_CODE_RE.fullmatch(country_code):
            raise RuleGenerationError(
                f"invalid country code {value!r}; CC must contain two-letter codes"
            )
        country_codes.add(country_code)
    if not country_codes:
        raise RuleGenerationError("CC did not contain any country codes")
    return country_codes


def networks_for_country(country_code):
    command = ["location", "list-networks-by-cc", country_code]
    try:
        result = subprocess.run(command, text=True, capture_output=True, check=False)
    except FileNotFoundError as exc:
        raise RuleGenerationError(
            "location is required; install the libloc location command"
        ) from exc
    if result.returncode != 0:
        detail = result.stderr.strip()
        if detail:
            detail = f": {detail}"
        raise RuleGenerationError(
            f"location list-networks-by-cc {country_code} failed{detail}"
        )

    found = False
    for line in result.stdout.splitlines():
        value = line.strip()
        if not value:
            continue
        try:
            network = ipaddress.ip_network(value, strict=True)
        except ValueError as exc:
            raise RuleGenerationError(
                f"location returned an invalid network for {country_code}: {value!r}"
            ) from exc
        found = True
        yield network
    if not found:
        raise RuleGenerationError(
            f"location list-networks-by-cc {country_code} returned no networks"
        )


def collect_networks(country_codes):
    ipv4_networks = []
    ipv6_networks = []
    for country_code in country_codes:
        for network in networks_for_country(country_code):
            if network.version == 4:
                ipv4_networks.append(network)
            else:
                ipv6_networks.append(network)
    return (
        list(ipaddress.collapse_addresses(ipv4_networks)),
        list(ipaddress.collapse_addresses(ipv6_networks)),
    )


def render_set(name, address_type, networks):
    lines = [
        f"\tset {name} {{",
        f"\t\ttype {address_type}",
        "\t\tflags interval",
        "\t\tauto-merge",
    ]
    if networks:
        lines.append("\t\telements = {")
        for index, network in enumerate(networks):
            suffix = "," if index + 1 < len(networks) else ""
            lines.append(f"\t\t\t{network}{suffix}")
        lines.append("\t\t}")
    lines.append("\t}")
    return "\n".join(lines)


def render_rules(country_codes, ipv4_networks, ipv6_networks):
    countries = " ".join(country_codes)
    return f"""# Generated by picosrv-nft-rules for CC={countries}
# This table is owned by picosrv. Docker and fail2ban tables are untouched.
# "add" is a no-op when the table exists, so the following delete always works.
add table inet picosrv_geo
delete table inet picosrv_geo

table inet picosrv_geo {{
{render_set("allowed_v4", "ipv4_addr", ipv4_networks)}

{render_set("allowed_v6", "ipv6_addr", ipv6_networks)}

\tchain geo_input {{
\t\ttype filter hook input priority 10; policy accept;

\t\t# GeoIP databases do not classify local and private source addresses.
\t\tip saddr {{ 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 }} return
\t\tip6 saddr {{ ::1/128, fc00::/7, fe80::/10 }} return

\t\tct state new tcp dport 443 ip saddr != @allowed_v4 counter drop
\t\tct state new tcp dport 443 ip6 saddr != @allowed_v6 counter drop
\t}}
}}
"""


def generate_rules():
    country_codes = country_codes_from_env()
    ipv4_networks, ipv6_networks = collect_networks(country_codes)
    return render_rules(country_codes, ipv4_networks, ipv6_networks)


def apply_rules(rules):
    try:
        result = subprocess.run(["nft", "-f", "-"], input=rules, text=True, check=False)
    except FileNotFoundError as exc:
        raise RuleGenerationError(
            "nft is required to apply the generated rules"
        ) from exc
    if result.returncode != 0:
        raise RuleGenerationError(f"nft -f - failed with status {result.returncode}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate picosrv country allow-list nftables rules"
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="apply the generated rules with nft -f - instead of printing them",
    )
    args = parser.parse_args()

    try:
        rules = generate_rules()
        if args.apply:
            apply_rules(rules)
        else:
            sys.stdout.write(rules)
    except RuleGenerationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
